// Public surface of the `links` module — the ONLY file other modules may import (ARCHITECTURE.md I-4).
export {
  createLink,
  updateLinkDestination,
  getLink,
  listLinks,
  createShortLink,
  listShortLinksForLink,
  resolveShortLinkByHostAndSlug,
  buildDestinationUrl,
  listDomains,
  createDomain,
  listFolders,
  createFolder,
  listTags,
  getOrCreateTag,
  tagLink,
  type Link,
  type ShortLink,
  type Domain,
  type Folder,
  type Tag,
  type CreateLinkInput,
  type CreateShortLinkInput,
  type ResolvedShortLink,
} from "./service";
